[config]
default_to_workspace = false

[tasks.build]
dependencies = ["build_web", "build_native"]

[tasks.build_native]
script='''
cargo build --release
'''

[tasks.run_wasm_pack]
script='''
wasm-pack build web --out-dir ../target/makefile/wasm_pack --out-name block_stacks --target web
'''

[tasks.build_web]
dependencies = ["run_wasm_pack"]
script='''
copy "web/build" "target/makefile/wasm_pack"
cd target/makefile/wasm_pack
npx --yes parcel build --no-source-maps --no-content-hash --dist-dir "../../../dist/web/" --public-url "./" index.html
'''