[config]
default_to_workspace = false

[tasks.build]
dependencies = ["build_web", "build_native"]

[tasks.build_native]
script_runner = "@shell"
script='''
cargo build --release
'''

[tasks.run_wasm_pack]
script_runner = "@shell"
script='''
wasm-pack build web --out-dir ../target/makefile/wasm_pack --out-name block_stacks --target web
'''

[tasks.setup_web_build]
dependencies = ["run_wasm_pack"]
script_runner = "@shell"
script='''
copy "web/build/" "target/makefile/wasm_pack/"
cd target/makefile/wasm_pack
npm install
'''

[tasks.run_parcel]
dependencies = ["setup_web_build"]
script_runner = "@shell"
script='''
cd target/makefile/wasm_pack
npx parcel build --no-source-maps --no-content-hash --dist-dir "build/" --public-url "./" index.html
'''

[tasks.run_posthtml]
dependencies = ["run_parcel"]
script_runner = "@shell"
script='''
cd target/makefile/wasm_pack
node posthtml.js
'''

[tasks.build_web]
dependencies = ["run_posthtml"]
script_runner = "@shell"
script='''
mkdir docs
copy "target/makefile/wasm_pack/build" "docs"
'''